name: Cache Dependencies
description: Cache dependencies to speed up workflows
inputs:
  cache-dependencies:
    description: 'Whether to cache the dependencies or not'
    required: false
    default: 'true'
  use-cache:
    description: 'Whether to use the cache or not'
    required: false
    default: 'true'
outputs:
  dummy-data:
    description: 'Whether the cache was used or not'
    value: ${{ steps.install.outputs.dummy-install-data }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.cache-dependencies == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      
    - name: Set cache dummy value
      id: set-cache-value
      run: echo "dummy-value=Hello dummy" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.use-cache != 'true'
      run: |
        npm ci
        echo "dummy-install-data=${{ steps.set-cache-value.outputs.dummy-value }}" >> $GITHUB_OUTPUT
        echo "Hello ${{ steps.set-cache-value.outputs.dummy-value }}"
      shell: bash
